"""Add collection is_public toggle and item resale_price_override

Revision ID: 5a8adc136bfa
Revises: 472adf64f560
Create Date: 2026-08-25 15:43:13.134528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8adc136bfa'
down_revision = '472adf64f560'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_column('asking_price')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        # Every collection that already exists today already has a live,
        # distributed share_token (the old "always shareable" design) — set
        # them all to public on backfill so nothing already shared breaks.
        # New collections default to private at the model level going
        # forward (Section 4 of the spec).
        batch_op.add_column(
            sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.alter_column('is_public', server_default=None)
        batch_op.alter_column('share_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resale_price_override', sa.Numeric(precision=10, scale=2), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('resale_price_override')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('share_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('is_public')

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asking_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
