"""Add name field to User

Revision ID: 743209d7372d
Revises: 5d5886f4fe17
Create Date: 2026-08-23 16:44:55.409830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743209d7372d'
down_revision = '5d5886f4fe17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
