"""Add collection description, share_token, and per-item asking_price

Revision ID: 8ecf2ca615a3
Revises: b458f2719c1c
Create Date: 2026-08-23 17:51:07.542218

"""
import secrets

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecf2ca615a3'
down_revision = 'b458f2719c1c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asking_price', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        # Nullable at first — existing rows need a backfilled token before
        # this can become NOT NULL, since there are already-created
        # collections in the live database.
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))

    connection = op.get_bind()
    collections_table = sa.table(
        "collections", sa.column("id", sa.Integer), sa.column("share_token", sa.String)
    )
    existing_ids = [row[0] for row in connection.execute(sa.select(collections_table.c.id))]
    for collection_id in existing_ids:
        connection.execute(
            collections_table.update()
            .where(collections_table.c.id == collection_id)
            .values(share_token=secrets.token_urlsafe(16))
        )

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('share_token', nullable=False)
        batch_op.create_index(batch_op.f('ix_collections_share_token'), ['share_token'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_share_token'))
        batch_op.drop_column('share_token')
        batch_op.drop_column('description')

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_column('asking_price')

    # ### end Alembic commands ###
